SELECT TOP (1000) [Patient_ID]
      ,[Age]
      ,[Gender]
      ,[Department]
      ,[Diagnosis]
      ,[Visit_Date]
      ,[Treatment_Cost]
      ,[Doctor_Name]
      ,[Hospital_Location]
      ,[Visit_ID]
  FROM [HealthDB].[dbo].[PatientRecords]
